apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - model-registry-secret.yaml
  - model-registry.yaml
  - model-registry-db-parameters.yaml
  - mysql-deployment.yaml
  - mysql-ns.yaml
  - mysql-pvc.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
