apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: rhoai-model-registries

resources:
  - model-registry-secret.yaml
  - model-registry.yaml
  - /mysql-db

patches:
  - path: patch-datasciencecluster.yaml
    target:
      kind: DataScienceCluster
