apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

components:
  - model-registry-secret.yaml
  - model-registry.yaml
  - model-registry-db-parameters.yaml
  - mysql-deployment.yaml
  - mysql-ns.yaml
  - mysql-pvc.yaml
  - mysql-secret.yaml
  - mysql-service.yaml
  - rolebinding.yaml

patches:
  - path: patch-datasciencecluster.yaml
    target:
      kind: DataScienceCluster
