apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../../../../../components/apps/model-registry/overlays/default

patches:
  - path: patch-datasciencecluster.yaml
    target:
      kind: DataScienceCluster
